### ISSUE TITLE
Update secp256k1-frost to secp256k1 4258c54f4ebf (bitcoin v25.x)

### ISSUE THREAD

**Issue by muxator** [bancaditalia/secp256k1-frost#18]
Secp256k1 version 4258c54f4ebf is the one that got into bitcoin **v25.0** and **v25.1**.

It got there via https://github.com/bitcoin/bitcoin/commit/f5fdd4e2799b318ff004b2349fd1e4176cb752fa.

secp256k1-frost needs to be rebased on that version before integrating https://github.com/bancaditalia/itcoin-core/pull/16

**Comment by matteonardelli** [comment]
PR #23 addresses this issue.
